apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: surya3456/inventory-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_APPLICATION_NAME
              value: inventory-service
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eurekaserver:8761/eureka
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://inventory-db:3306/inventory_db
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
